[package]
name = "clipboard_native"
version = "0.1.0"
edition = "2021"

[lib]
name = "clipboard_native"
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2.0", features = ["derive"] }
arboard = "2.3.0"
base64 = "0.21"
tokio = { version = "1", features = ["rt", "macros", "time"] }
