name: Generate SBOM

on:
  push:
    branches:
      - main

jobs:
  build-sbom:
    name: Build CycloneDX SBOM (always succeed)
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install CycloneDX NPM Plugin
        run: npm install --no-save @cyclonedx/cyclonedx-npm
        continue-on-error: true

      - name: Generate SBOM (CycloneDX)
        run: |
          npx cyclonedx-bom --output bom.xml || echo "CycloneDX generation failed, continuing..."

      - name: Upload SBOM artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cyclonedx-sbom
          path: |
            bom.xml
            # if bom.xml doesn’t exist, upload nothing but still succeed
